# Site settings
title: "Suhas Vijayakumar"
author: "Suhas Vijayakumar"
description: "This? <br> This is my home on the internet. Views expressed in this corner of the internet are my own, and do not necessarily reflect the views or opinions of anyone else."
keywords: "neuroscience, education, scicomm, teaching, science"
biography: "I'm currently a post-doc at the <a target='_blank' href='https://projects.iq.harvard.edu/evolutionaryneurosciencelab/home'>Evolutionary nueorscience lab</a> of Harvard University. Here are my <a target='_blank' href='https://repository.ubn.ru.nl/bitstream/handle/2066/226799/226799.pdf?sequence=1'>PhD Thesis</a> and my <a href='/assets/resume.pdf'>Résumé</a>. Or go to <a href='/phd_defense'>PhD defense</a> page to know more about that and see my thesis cover page."
thanks: "This site is based on <a target='_blank' href='https://github.com/hugoferreira/papyrus-theme'>Papyrus theme</a>, by Prof. Dr. Hugo Sereno Ferreira, and his blog. You can find his blog here <a target='_blank' href='http://hugosereno.eu/'>http://hugosereno.eu/</a>."
colophon: "© 2021 by Suhas Vijayakumar.<br>Content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (BY-NC-SA)</a> unless otherwise noted.<br>This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

baseurl: ""
url: "http://suhasvijayakumar.in/"

twitter_username: neuroacademic
github_username: suhasvijayakumar
linkedin_username: suhas-vijayakumar
instagram_username: academic_story
google_scholar: https://scholar.google.com/citations?user=w4ZMUwEAAAAJ&hl=en
contact_email: mailto:vijayakumar.suhas@gmail.com


google-analytics:

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

kramdown:
  parse_block_html: true

collections:
  tags:
    output: true
    permalink: tags/:path/

plugins:
- jekyll-sitemap
